"""added is_deleted soft delete column

Revision ID: 2acc88e21cdb
Revises: fde0e3a4290a
Create Date: 2026-06-15 16:52:06.953703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acc88e21cdb'
down_revision: Union[str, Sequence[str], None] = 'fde0e3a4290a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_deleted')
    # ### end Alembic commands ###
