"""add columns project_name and is_deleted in project table

Revision ID: 61981a5a83f3
Revises: 2acc88e21cdb
Create Date: 2026-06-16 12:13:13.864173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61981a5a83f3'
down_revision: Union[str, Sequence[str], None] = '2acc88e21cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###
