"""initial model create and seeds

Revision ID: b465bcb3de70
Revises: 
Create Date: 2026-06-12 15:36:38.315045

"""
from typing import Sequence, Union
from app.utils.passwords.password_helper import PasswordHelper
from datetime import datetime

from alembic import op
import sqlalchemy as sa

from app.core.config.config import settings


# revision identifiers, used by Alembic.
revision: str = 'b465bcb3de70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(), nullable=False),
    sa.Column('organization_domain_name', sa.String(), nullable=False),
    sa.Column('org_admin_name', sa.String(), nullable=False),
    sa.Column('org_admin_email', sa.String(), nullable=False),
    sa.Column('subscription_name', sa.Enum('FULL', 'HALF', 'BASIC', name='subscriptiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(), nullable=False),
    sa.Column('allowed_resource', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('subscription_name', sa.Enum('FULL', 'HALF', 'BASIC', name='subscriptiontype'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('subscription_name')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Enum('STRATEGIC', 'COMPLIANCE', 'OPERATIONAL', 'OTHER', name='projecttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attachments',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_ref', sa.String(), nullable=False),
    sa.Column('added_by', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('role_type', sa.Enum('SYSTEM', 'CUSTOM', name='roletype'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_title', sa.String(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_deadline', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('state', sa.Enum('IN_PROGRESS', 'COMPLETED', 'TODO', name='taskstate'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_columns',
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('column_title', sa.String(), nullable=False),
    sa.Column('column_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('column_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('project_member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='unique_member_per_project')
    )
    # ### end Alembic commands ###
    connection = op.get_bind()

    #=========== Policies Seeding ============
    policy_ids = settings.POLICY_IDS
    policy_names = settings.POLICY_NAMES
    allowed_resources = settings.ALLOWED_RESOURCES

    for i in range(0, len(policy_ids)):
        connection.execute(
                sa.text("""
                    INSERT INTO policies (
                        policy_id,
                        policy_name,
                        allowed_resource,
                        created_at
                    )
                    VALUES (
                        :policy_id,
                        :policy_name,
                        :allowed_resource,
                        :created_at
                    )
                """),
                [
                    {
                        "policy_id": policy_ids[i],
                        "policy_name": policy_names[i],
                        "allowed_resource": allowed_resources[i],
                        "created_at": datetime.now(),
                    }
                ]
            )    
    #====================================
    #================= SUPER ADMIN SEED ============
    connection = op.get_bind()

    #=========== Policies Seeding ============
    connection.execute(
            sa.text("""
                INSERT INTO users (
                    user_id,
                    organization_id,
                    email,
                    name,
                    hashed_password,
                    is_active,
                    created_at
                )
                VALUES (
                    :user_id,
                    :organization_id,
                    :email,
                    :name,
                    :hashed_password,
                    :is_active,
                    :created_at
                )
            """),
            [
                {
                    "user_id":settings.SUPERADMIN_USER_ID,
                    "organization_id": None,
                    "email":settings.SUPERADMIN_EMAIL,
                    "name":settings.SUPERADMIN_NAME,
                    "hashed_password": PasswordHelper.hash_password(settings.SUPERADMIN_PASSWORD),
                    "is_active":True,
                    "created_at":datetime.now(),
                }
            ]
        )   

    # ========= user_policy_seed ===========
    connection.execute(
            sa.text("""
                INSERT INTO user_policy (
                    id,
                    user_id,
                    policy_id,
                    assigned_at
                    )
                VALUES (
                    :id,
                    :user_id,
                    :policy_id,
                    :assigned_at
                )
            """),
            [
                {
                    "id":"03b5d51c-aacf-47ad-a916-b6ba611ce1ab",
                    "user_id":settings.SUPERADMIN_USER_ID,
                    "policy_id":"c454023f-e6a9-442f-8725-81e4fb226631",
                    "assigned_at":datetime.now(),
                }
            ]
        )   

    # ========== Subscription Plan Seeding ======
    subscription_plan_ids = settings.SUBSCRIPTION_PLAN_IDS
    subscription_plan_names = settings.SUBSCRIPTION_PLAN_NAMES
    subscription_plan_costs = settings.SUBSCRIPTION_PLAN_COSTS
    subscription_plan_details = settings.SUBSCRIPTION_PLAN_DETAILS

    for i in range (0, len(subscription_plan_ids)):
        connection.execute(sa.text("""
                INSERT INTO subscriptions (
                    subscription_id,
                    subscription_name,
                    cost,
                    details,
                    created_at
                    )
                VALUES (
                    :subscription_id,
                    :subscription_name,
                    :cost,
                    :details,
                    :created_at
                )
            """),
            [
                {
                    "subscription_id":subscription_plan_ids[i],
                    "subscription_name":subscription_plan_names[i],
                    "cost":subscription_plan_costs[i],
                    "details":subscription_plan_details[i],
                    "created_at": datetime.now()
                }
            ]
        )   




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_member')
    op.drop_table('comments')
    op.drop_table('workflow_columns')
    op.drop_table('user_policy')
    op.drop_table('tasks')
    op.drop_table('roles')
    op.drop_table('attachments')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('organizations')
    op.drop_table('subscriptions')
    op.drop_table('policies')
    # ### end Alembic commands ###
