"""add column is_active in organizations table and unique constraing in org_admin_email

Revision ID: fde0e3a4290a
Revises: b465bcb3de70
Create Date: 2026-06-15 11:55:18.171490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde0e3a4290a'
down_revision: Union[str, Sequence[str], None] = 'b465bcb3de70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['org_admin_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'is_active')
    # ### end Alembic commands ###
